### ekf config file ###
ekf_filter_node:
        ros__parameters:
                frequency: 30.0

                two_d_mode: false

                # Whether to publish the acceleration state. Defaults to false if unspecified.
                publish_acceleration: false

                # Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
                publish_tf: false
                map_frame: map # Defaults to "map" if unspecified
                odom_frame: odom # Defaults to "odom" if unspecified
                base_link_frame: base_link # Defaults to "base_link" if unspecified
                world_frame: odom # Defaults to the value of odom_frame if unspecified
                # odom0: /odom_diff
                # odom0_config: [true,  true,  true,
                #                false, false, false,
                #                false, false, true,
                #                false, false, false,
                #                false, false, false]
                odom0: /odom_diff
                odom0_config: [false, false, false, 
                               false, false, false, 
                               true, true, false,  
                               false, false, true,  
                               false, false, false] 
                odom0_differential: false
                odom0_relative: false

                imu0: /imu
                imu0_config: [false, false, false,
                              true,  true,  true,
                              false, false, false,
                              false, false, false,
                              false, false, false]            
                imu0_differential: true
                imu0_relative: true
        


